//
//  ContatoInteractor.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 04/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContatoBusinessLogic
{
  func doSomething(request: Contato.Something.Request)
}

protocol ContatoDataStore
{
  //var name: String { get set }
}

class ContatoInteractor: ContatoBusinessLogic, ContatoDataStore
{
  var presenter: ContatoPresentationLogic?
  var worker: ContatoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Contato.Something.Request)
  {
    worker = ContatoWorker()
    worker?.doSomeWork()
    
    let response = Contato.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
