//
//  InvestimentoModels.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 02/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Investimento
{
  // MARK: Use cases
    enum type: Int{
        case field = 1
        case text = 2
        case image = 3
        case checkbox = 4
        case send = 5
    }
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
