//
//  InvestimentoViewController.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 02/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentoDisplayLogic: class
{
  func displaySomething(viewModel: Investimento.Something.ViewModel)
}

class InvestimentoViewController: UIViewController, InvestimentoDisplayLogic
{
  var interactor: InvestimentoBusinessLogic?
  var router: (NSObjectProtocol & InvestimentoRoutingLogic & InvestimentoDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestimentoInteractor()
    let presenter = InvestimentoPresenter()
    let router = InvestimentoRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
   
    }
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Investimento.Something.Request()
    interactor?.doSomething(request: request)
  }
  
    @IBOutlet weak var titleLabel: UILabel!
    func displaySomething(viewModel: Investimento.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
   
    
    
  }
}
