//
//  InvestimentoPresenter.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 02/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentoPresentationLogic
{
  func presentSomething(response: Investimento.Something.Response)
}

class InvestimentoPresenter: InvestimentoPresentationLogic
{
  weak var viewController: InvestimentoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Investimento.Something.Response)
  {
    let viewModel = Investimento.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
