//
//  InvestimentoInteractor.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 02/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentoBusinessLogic
{
  func doSomething(request: Investimento.Something.Request)
}

protocol InvestimentoDataStore
{
  //var name: String { get set }
}

class InvestimentoInteractor: InvestimentoBusinessLogic, InvestimentoDataStore
{
  var presenter: InvestimentoPresentationLogic?
  var worker: InvestimentoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Investimento.Something.Request)
  {
    worker = InvestimentoWorker()
    worker?.doSomeWork()
    
    let response = Investimento.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
