//
//  InvestimentoViewController.swift
//  TesteiOS
//
//  Created by marcus.v.seixas on 02/05/18.
//  Copyright (c) 2018 marcus.v.seixas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentoDisplayLogic: class
{
  func displaySomething(viewModel: Investimento.Something.ViewModel)
}

class InvestimentoViewController: UIViewController, InvestimentoDisplayLogic
{
  var interactor: InvestimentoBusinessLogic?
  var router: (NSObjectProtocol & InvestimentoRoutingLogic & InvestimentoDataPassing)?
  let fundLink = "https://floating-mountain-50292.herokuapp.com/fund.json"
  var fundDict: NSDictionary = [:]
  @IBOutlet weak var titleLabel: UILabel?
  @IBOutlet weak var fundNameLabel: UILabel!
  @IBOutlet weak var whatIsLabel: UILabel!
  @IBOutlet weak var definitionLabel: UILabel!
    @IBOutlet weak var riskTitleLabel: UILabel!
    @IBOutlet weak var riskLabel: UILabel!
    @IBOutlet weak var infoTitleLabel: UILabel!
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestimentoInteractor()
    let presenter = InvestimentoPresenter()
    let router = InvestimentoRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    self.tabBarItem = UITabBarItem(title: "Investimento", image: nil, selectedImage: nil)
    getJsonFromUrl()
    }
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    //getJsonFromUrl()
    
    let request = Investimento.Something.Request()
    interactor?.doSomething(request: request)
  }
  
    
    func displaySomething(viewModel: Investimento.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
    self.titleLabel?.text = fundDict.value(forKey: "title") as? String
    self.fundNameLabel.text = fundDict.value(forKey: "fundName") as? String
    self.whatIsLabel.text = fundDict.value(forKey: "whatIs") as? String
    self.definitionLabel.text = fundDict.value(forKey: "definition") as? String
    self.riskTitleLabel.text = fundDict.value(forKey: "riskTitle") as? String
    self.riskLabel.text = fundDict.value(forKey: "risk") as? String
    self.infoTitleLabel.text = fundDict.value(forKey: "infoTitle") as? String
  }
    
    func getJsonFromUrl(){
        //creating a NSURL
        let url = NSURL(string: fundLink)
        
        //fetching the data from the url
        URLSession.shared.dataTask(with: (url as URL?)!, completionHandler: {(data, response, error) -> Void in
            
            if let jsonObj = try? JSONSerialization.jsonObject(with: data!, options: .allowFragments) as? NSDictionary {
                self.fundDict = jsonObj!.value(forKey: "screen")! as! NSDictionary
            }
        }).resume()
    }
}
